### ISSUE TITLE
Embed image assets in the material demo – to avoid CORS issues

### ISSUE THREAD

**Issue by kevmoo** [flutter/samples#1844]
![image](https://github.com/flutter/samples/assets/17034/705c9e3a-b769-40d2-b766-f6ce983cc010)

See https://flutterweb-wasm.web.app/#/ –

**Comment by kevmoo** [comment]
CC @domesticmouse @johnpryan

**Comment by johnpryan** [comment]
I don't think it's a CORS issue, it looks like these URLs are broken, but I agree we should remove the dependency on https://github.com/flutter/assets-for-api-docs 

The correct links should have`/blob/main` or something similar, for example https://github.com/flutter/assets-for-api-docs/blob/main/assets/material/content_based_color_scheme_1.png

**Comment by kevmoo** [comment]
FYI: also here - https://flutter.github.io/samples/web/material_3_demo/#/

Maybe GitHub changed some config? Or did we stop publishing something?

**Comment by johnpryan** [comment]
Disregard my previous comment, we need  to get the GitHub Pages hosting for the assets-for-api-docs repo working again. We need https://flutter.github.io/assets-for-api-docs/assets/material/content_based_color_scheme_1.png to return the image, since they need to be the same domain for CORS.

cc: @QuncCccccc  @gspencergoog

**Comment by gspencergoog** [comment]
Yes, working on it.

**Comment by QuncCccccc** [comment]
Looks like the images are back! 🎉
https://flutter.github.io/samples/web/material_3_demo/#/

**Comment by gspencergoog** [comment]
Yeah, Godofredo updated the settings, so it's back.
