### ISSUE TITLE
Problems with https://flutter.github.io/samples/, unable to copy code

### ISSUE THREAD

**Issue by VladyslavBondarenko** [flutter/samples#310]
In https://flutter.github.io/samples/ I can see such errors in the developer console

![image](https://user-images.githubusercontent.com/17024977/73731642-82bb9800-4741-11ea-934a-3633ed7ee972.png)

And I have 
```
natives.dart:14 Overflow on channel: flutter/platform.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
```
every time when trying to copy the code via copy button. So the copy button is not working

![image](https://user-images.githubusercontent.com/17024977/73731759-bc8c9e80-4741-11ea-9082-9eb5889a9c36.png)

**Comment by rami-a** [comment]
So this is a known issue, and there was a recent fix in flutter/flutter to support clipboard on web. However, we chose to use a slightly older commit on the master branch to deploy the web gallery due to this issue with flare assets https://github.com/flutter/flutter/issues/49429 that we deemed more important in the short term.

Once https://github.com/flutter/flutter/issues/49429 is fixed, we can re-deploy gallery with the latest master

**Comment by RedBrogdon** [comment]
@rami-a Do you have the ability to transfer this to the repo where you track Gallery issues?

**Comment by rami-a** [comment]
@RedBrogdon unfortunately it looks like you can only transfer issues to repos in the same org.

So we could either keep this open here or just recreate the same issue in https://github.com/material-components/material-components-flutter-gallery/issues. Which do you prefer?

**Comment by RedBrogdon** [comment]
I'd prefer to close and recreate it to be with the other gallery-specific issues, unless that's onerous for y'all.

**Comment by rami-a** [comment]
Sounds good, created https://github.com/material-components/material-components-flutter-gallery/issues/542 to track

**Comment by rami-a** [comment]
@VladyslavBondarenko I just re-deployed the gallery with flutter master and copy/paste should work now.
