### ISSUE TITLE
[animations] Add Animation Sample

### ISSUE THREAD

**Issue by aksayushx** [flutter/samples#382]
Hey @RedBrogdon @johnpryan , 
I would like to add a simple Slide Transition widget demo to the basics/ of animations which is missing from it. 
Should I go ahead and begin working on it?

**Comment by jddeep** [comment]
Hi @aksayushx Thanks for filing an issue. 
Quoting @johnpryan regarding this:
> We don't need all the transition widgets, just one example of an AnimatedWidget (e.g. FadeTransition). Providing a link to AnimatedWidget will let users discover more *Transition widgets.

So the work for the AnimatedWidget sample - FadeTransition in this case has been already going on in #375.

**Comment by aksayushx** [comment]
No problem. 
I have an animation idea using CurvedAnimation which will be suitable for the misc section of animations. So I ll be working on that. Thanks ;)

**Comment by RedBrogdon** [comment]
@aksayushx, can you tell us a little about what you have in mind, and how it would complement the demos that are already in the app?

**Comment by aksayushx** [comment]
Hey @RedBrogdon I am almost done with it and it looks here is a gif of the animation .
![ezgif com-crop](https://user-images.githubusercontent.com/55887638/76909096-4f3b6400-68d0-11ea-8755-916d6ab53177.gif)
Should I add it to misc section and make a new PR?

**Comment by RedBrogdon** [comment]
Maybe I can help by talking over some of the things I think about when creating a sample. This is how the process tends to work for me:

1) What is the goal for the sample?

This repo is maintained by Flutter's developer relations team, and a phrase we frequently use on the DevRel team is "[learning outcome](https://teaching.utoronto.ca/teaching-support/course-design/developing-learning-outcomes/what-are-learning-outcomes/)." A learning outcome is the goal for an educational exercise -- what a student should gain by going through it. In this case, what should a developer who reads through your CurvedAnimation sample come away with? Should they:

* Just know that CurvedAnimation exists? 
* Know how to call its constructor and create one?
* Know how to combine it with other classes that it would normally be used with?
* Understand what an Animation object is?
* Understand what "curve" means in this context?

Sample code is different than demo code or app code. It exists first and foremost to educate, so it's important to know exactly what educational goals you have.

2) What do I need to show in order to achieve the learning outcome?

Once you know what you're aiming at, you can start thinking about how to get it. How can you guide someone in a simple and easily understood way to the outcome you want them to achieve? Say you chose these two learning outcomes:

* Know how to call CurvedAnimation's constructor and create one.
* Understand what "curve" means in this context.

If these are your learning goals, you might create a StatefulWidget that builds a CurvedAnimation using different curves. You could give the user a dropdown list to pick a curve, and a button to re-run the animation so they can experiment. You might also pick a different animation than a spinning logo, one that'll make it easier to see the curve in action.

3) What *don't* I need to show in order to achieve the learning outcome?

This part is really important. Just like every bit of code you add to an app can bloat it and slow it down, every bit of code you add to a sample can slow down someone trying to learn from it. We often refer to this as [cognitive load](https://en.wikipedia.org/wiki/Cognitive_load).

The smaller you can make a sample, the better you'll generally be, so any extraneous theming, customization, and so on, should be removed.

Given all of this, what would you say your goals are for the CurvedAnimation sample? What would you like people to learn from viewing it?

**Comment by aksayushx** [comment]
Through my sample I intend any developer going through it to :
1. Understand what 'curve' means in this context
2. Know how to combine it with other classes it is used with.  

I intend to show a nice application of the CurvedAnimation class in combination of few others through the rotating logo animation. I want to use just one curve for forward animation and one for reverse so that anyone looking into it gets an idea of the functionality of these curves and can research and try more curves in their own way. 
I will remove the extra customisation and keep it simple enough so as to only serve my learning outcomes.

**Comment by RedBrogdon** [comment]
Sounds like a great plan.

**Comment by aksayushx** [comment]
Thanks @RedBrogdon 
I ll send a PR soon making necessary changes.
