### ISSUE TITLE
[provider_shopper] Add Widget Tests

### ISSUE THREAD

**Issue by jddeep** [flutter/samples#387]
In the `provider_shopper` sample app, we have a widget test already there for demonstration here - https://github.com/flutter/samples/blob/master/provider_shopper/test/widget_test.dart.
I suggest including a driver test for the app as well for demonstration of integration tests. The driver test itself should be pretty straight forward according to the app functioning.

**Comment by jddeep** [comment]
@RedBrogdon @domesticmouse What do you think about this? Should we include one?

**Comment by RedBrogdon** [comment]
Flutter driver tests have a layer of complexity that Dart unit tests and Flutter widget tests do not, since they're normally expected to run on a hardware device.

We've avoided having driver tests in this repo for that reason, with the only exception being the driver tests that are called indirectly by the espresso tests in one of the add-to-app samples. Just to get that to work we had to integrate Firebase Test Lab to our CI setup, which is something I'd prefer to leave as-is until the rest of the add-to-app testing is sorted.

All that said, if you'd like to add some *widget* tests to provider_shopper, that would be a great idea for a PR. Flutter driver is a different animal, though.

**Comment by jddeep** [comment]
@RedBrogdon True, yes driver tests require a device to instrument the app and run on. But I thought since there is a lack of examples for integration testing in apps. Users/devs can clone the sample and run the tests with the help of their own hardware device to check the tests live using `flutter drive`. They'll get a clearer idea about the tests. Actually this is also something along with unit and widget tests to be demonstrated in a separate app altogether in the repo. Please let me know your thoughts on that :)
Also, I'll look into on adding some widget tests for `provider_shopper` as well. Thanks.

**Comment by RedBrogdon** [comment]
My concern is that any tests we write for the apps need to be run as part of our continuous integration setup, so we can be confident that they're always working. If additional flutter driver tests are added, we'll need to find a way to run them via Firebase Test Lab, which has additional maintenance cost (both in time and literal dollars!). For that reason, it's a more complicated enterprise.

Unit and widget tests, on the other hand, work very well with our current setup, and many of our apps are in desperate need of better unit and widget tests. That's why I was encouraging work on them.

**Comment by AyushBherwani1998** [comment]
@RedBrogdon I agree with your points and also that sample apps in the repo require better unit and widget test. Many of the samples only check if the `Text` is correctly rendered or not. For example, the sample app showing animations.

Can I generate a new Issue for improving the tests for sample animations app and start working on it?

**Comment by RedBrogdon** [comment]
Sure. It's possible @jddeep may also want to contribute unit/widget tests, and it'd be good to make sure you and he don't accidentally start working on tests for the same app at the same time.

Thanks to both of you, by the way, for contributing not just code, but also conversation. It's a big part of how we maintain good, positive culture for our repo.

**Comment by AyushBherwani1998** [comment]
Yes, I agree with you @RedBrogdon. Communication and creating Issues before sending the PR is really important. Thanks for being an awesome mentor. 
Hey, @jddeep I have created a new Issue regarding improving unit/widget tests. If you are done with improving the unit/widget test for provider_shopper, we can also split the work for animation sample; this way, we both can get exposure to writing the test.

**Comment by jddeep** [comment]
> If additional flutter driver tests are added, we'll need to find a way to run them via Firebase Test Lab, which has additional maintenance cost (both in time and literal dollars!). For that reason, it's a more complicated enterprise.

@RedBrogdon Ah! Now I understand the reason. Thanks for the info:)
I'll refactor this issue for providing widget tests for `provider_shopper` now.
Hey @AyushBherwani1998 sure, you can start work for the `animations` app. Once, I am done with this and other apps, I'll join in with you.
