### ISSUE TITLE
[visual sample index] Improve cookbook screenshots

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#394]
Cookbook screenshots should include a screenshot of the running app, most likely the DartPad iframe on the page.

[Cookbook scraper instructions](https://github.com/flutter/samples/blob/master/web/samples_index/README.md#generating-cookbook-content)

[Cookbook scraper source code](https://github.com/flutter/samples/blob/master/web/samples_index/lib/cookbook.dart)

**Comment by mohak852** [comment]
I wanna work on this issue. @RedBrogdon @johnpryan

**Comment by johnpryan** [comment]
@mohak852 I added some links to the relevant code and README - let me know if you have any questions.

**Comment by mohak852** [comment]
@johnpryan Should I begin with one cookbook tutorial and then proceed for the other or should I add all together in one single go?

**Comment by johnpryan** [comment]
The scraper needs to be modified to inspect the DartPad iframe. Once it's modified it will update all the screenshots.

**Comment by tusharojha** [comment]
Hi @johnpryan 
I am interested to solve this issue but since it's my first try with this project. I think this line [https://github.com/flutter/samples/blob/master/web/samples_index/lib/cookbook.dart#L57](line) takes the screenshot which later gets saved but how am I supposed to inspect the DartPad iframe.

I tried to read more on this over the internet but didn't find many resources, but a workaround is to crop the screenshot but that's also not the case here. It would be great if you can suggest to me the right path to follow.

**Comment by johnpryan** [comment]
I haven't looked into it, but the idea is to load page declared in the `src` attribute of the iframe and then take a screenshot.

**Comment by ericwindmill** [comment]
Closing, as the samples index is being deprecated
