### ISSUE TITLE
Rover' Guide

### ISSUE THREAD

**Issue by irahulcse** [flutter/samples#418]
From quite some time, I had been working on a Project named as  Rover's Guide (One Stop Solution for Travellers). In this project, I had used different types of widgets like Circle Avatar, Expanded Widgets etc. 
It is a full-fledge project deployed on the web using Flutter Web and GitHub Actions. As I am also looking to contribute to GSoC 2020 on Platform Channel Sample App( Proposal Submitted). So this issue/pr could be a good start for me for contributions towards Sample Repo

Repo, can be found on ths [link](https://github.com/irahulcse/Rovers_Guide_Fluter).
Thanks, looking forwards to a wonderful summer in this pandemic.

**Comment by johnpryan** [comment]
Looks great! We [don't typically add third-party samples](https://github.com/flutter/samples/blob/master/CONTRIBUTING.md#is-this-the-right-place-for-your-contribution) to this project since we maintain them here, they can get out of sync, etc.

You can also submit your app to [It's All Widgets](https://itsallwidgets.com/) to share it more widely. Thanks!
