### ISSUE TITLE
We should add an flutter translation app using flutter localization package and intl translation

### ISSUE THREAD

**Issue by mohak852** [flutter/samples#483]
So as flutter is used globally in many apps there are difficulties for the app to only be specified to one language. Flutter localization package provides you to convert the app into many native languages. We should add a sample demonstrating the flutter localization example.

Would you like to work on this issue? 
YES

**Comment by mohak852** [comment]
@RedBrogdon What do you think about this?

**Comment by mohak852** [comment]
@domesticmouse Can you guide me that should I proceed or not with this sample

**Comment by RedBrogdon** [comment]
Hi, @mohak852!

Let's talk about what you're imagining would be in the sample, what its goals would be, and how it differs from existing resources. Before investing a ton of time, it'd be good to answer the following questions:

* What resources exist outside this repo for developers looking to learn about i18n and localization?
  - The [Flutter Gallery](github.com/flutter/gallery) is a sample that includes the `intl` package. Are there others to be found? Does [Awesome Flutter](https://github.com/Solido/awesome-flutter) list anything?
  - There's also the sample code in the [internationalization guide](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-using-the-dart-intl-tools) on flutter.dev
  - What would this new sample add to the ecosystem?
* What, in particular, would the new sample be trying to teach people?
  - Is it a general introduction to the `intl` package?
    * If so, would it be better for it to be kept in that package's repo?
* Does the sample need to be a full app? Could it instead be a blog post that includes code snippets?
* Does the sample really *need* to be maintained in this repo? Could it exist in its own?
  - This is a really important question, since this repo already has a ton of projects in it, and we need to keep it as small as possible.
  - The samples maintained elsewhere aren't any less "official" than the ones seen here. Many very popular projects are linked in indices like Awesome Flutter.

**Comment by mohak852** [comment]
@RedBrogdon  Actually I got your point but in the flutter docs, they have not clearly mentioned about the flutter localization for me I also have to research about this for a long time and then I achieved at that goal to change my language and I'm trying to address this because there are a lot of people who are struggling how to manage this package. That is the reason why I am interested to add this thing in the sample repo
