### ISSUE TITLE
Addition of horizontal rules in infinitelist app

### ISSUE THREAD

**Issue by arteevraina** [flutter/samples#491]
![Screenshot_1594210969](https://user-images.githubusercontent.com/43968121/86918170-e78d7b00-c143-11ea-966a-4af88ff0b725.png)

Here, between after each color palette we can add a horizontal rule. Can I add this @RedBrogdon ?

**Comment by gaurivn** [comment]
I'm a first-timer here. Is this issue approved and available? If yes, I would like to work on this issue.

**Comment by arteevraina** [comment]
Hi! @gaurivn . This is issue not approved yet.

**Comment by gaurivn** [comment]
Okay, when it gets approved please assign me

**Comment by abd99** [comment]
Thanks, @arteevraina for filing an issue. I'm happy to see that @gaurivn and you are willing to contribute to the repo.

Every sample in the repo has its own goals. The main goal of the infinitelist sample is to show asynchronous pagination so that it appears as an infinite list to the user. It doesn't feel like adding a horizontal rule would contribute towards the goals of the sample. Also, all the samples are built in the easiest and the most unclever way possible, avoiding all the unnecessary things. This makes it easier for anyone going through the code to learn from it.

**Comment by arteevraina** [comment]
Sure @abd99 ! Will look for some other issues to contribute :)
