### ISSUE TITLE
bug in provider_counter sample

### ISSUE THREAD

**Issue by heroqin** [flutter/samples#495]
in provider_counter sample, I add a print line before 'return Scaffold' as following:
![图片](https://user-images.githubusercontent.com/48232744/87399993-c79a0380-c5ea-11ea-8d32-f306a9649131.png)
then comment the 'Consumer' block and add a Text line as following:
![图片](https://user-images.githubusercontent.com/48232744/87400178-1051bc80-c5eb-11ea-9fcd-084ec28b7362.png)

then Debug Run(F5), as expected, Debug Console printed out the following message when I click the button:
I/flutter (13843): MyHomePage build called

then I uncomment the 'Consumer' block and comment the Text line as following: 
![图片](https://user-images.githubusercontent.com/48232744/87400550-8e15c800-c5eb-11ea-9fa2-680a25382990.png)
and Debug Console said:
Reloaded 1 of 506 libraries in 373ms.
then I clicked the button, but the Debug Console still said:
I/flutter (13843): MyHomePage build called

I'm very confused: Why does 'MyHomePage build called' still be printed out? and I restart the app(Ctrl+Shift+F5),  and then click the button, no 'MyHomePage build called' output in Debug Console.

So I wonder hot reload have something wrong handling provider.

**Comment by abd99** [comment]
Thanks for filing an issue, @heroqin. 
> I'm very confused: Why does 'MyHomePage build called' still be printed out? 

The reason behind this is that whenever the hot reload takes place, the build method is called and the entire widget is rebuilt. Hence, the message is printed on the console.

> and I restart the app(Ctrl+Shift+F5), and then click the button, no 'MyHomePage build called' output in Debug Console.

In this case, only the widgets dependent on the Consumer are rebuilt.

So if you would have done something like this,
```
Consumer<Counter>(
              builder: (context, counter, child) {
                print('Build called');
                return Text(
                  '${counter.value}',
                  style: Theme.of(context).textTheme.headline4,
                );
             },
),
```
it would still have been printed on the console when you hit the button.

Visit https://pub.dev/documentation/provider/latest/provider/Consumer-class.html for more info on Consumer.

I hope your query is solved now.

**Comment by heroqin** [comment]
I'm sorry for my poor english, so maybe you misunderstood what I mean. I try to re-edit what I said using italic words as following, and hope you can understand:

in provider_counter sample, I add a print line before 'return Scaffold' as following:
 ![图片](https://user-images.githubusercontent.com/48232744/87399993-c79a0380-c5ea-11ea-8d32-f306a9649131.png)
 then comment the 'Consumer' block and add a Text line as following:
 ![图片](https://user-images.githubusercontent.com/48232744/87400178-1051bc80-c5eb-11ea-9fcd-084ec28b7362.png)
 
 then Debug Run(F5), as expected, Debug Console printed out the following message when I click the button:
 I/flutter (13843): MyHomePage build called
 
 then I uncomment the 'Consumer' block and comment the Text line as following:
 ![图片](https://user-images.githubusercontent.com/48232744/87400550-8e15c800-c5eb-11ea-9fa2-680a25382990.png)
 and Debug Console said:
**_I/flutter ( 3289): MyHomePage build called_**
 Reloaded 1 of 506 libraries in 373ms.

_(As you say, 'MyHomePage build called' is printed out before 'Reloaded 1 of 506 libraries in 373ms' when hot reload take place. I can understand this.)_

_but since I have uncommented the Consumer block and commented the Text line, after hot reload,  if I try to click the floating action button, builder of Consumer should be called and build() method of MyHomePage should not be called.
But when I clicked the button,  the Debug Console still said:_
 I/flutter (13843): MyHomePage build called
 
 _I'm very confused: Why does 'MyHomePage build called' still be printed out after I uncomment the Consumer block and comment the Text line(and certainly after hot reload)?_ 

_and I try to restart the app(Ctrl+Shift+F5), and then click the floating action button, no 'MyHomePage build called' output in Debug Console, that's the normal situation, and I can understand._
 
So I wonder hot reload have something wrong handling provider.

**Comment by RedBrogdon** [comment]
Thanks for posting this, @heroqin. It's a really interesting question.

What you're seeing is part of the normal behavior of Flutter hot reload, though it's not exactly obvious what's going on. Let me try and describe the steps:

1) First, you comment out the Consumer and add a Text widget that calls Provider.of<Counter>() with the BuildContext that MyHomePage gets in its build method.
2) This causes MyHomePage to run some code to *inherit* from an instance of Provider higher in the tree. As part of that process, the Provider's element remembers the BuildContext that was given to it as its inheritor.
3) Then, you remove that Text widget and add a Consumer, and hot reload the app.
4) Hot reload [does the following things](https://flutter.dev/docs/development/tools/hot-reload#how-it-works):
  a) First, it swaps any new Dart code into the running VM, replacing some of the old code.
  b) Then, it marks the entire render tree as "need repaint/relayout/recomposite" and the entire element tree as "needs build."
  c) This causes all the widgets in the tree to be rebuilt from the top down. Your Consumer is rebuilt and also inherits from the same Provider widget.
  d) Hot reload does *not* by default throw out any State objects or the Elements themselves, though!
  e) As a result, the Element from Step 2 (that is remembering the BuildContext given to it in that step) *stays in place* and keeps remembering that BuildContext.

At the end of this process, The Provider's element is now tracking *two* build contexts: the one for MyHomePage and the one for the Consumer. That's why you continue to see MyHomePage rebuild when you click the button. When you finally do a hot restart, all those elements *are* thrown away, the BuildContexts are forgotten, and the app is rebuilt from scratch, which is why the behavior goes away.

Keeping the Elements (and State objects, though we're not really discussing those right now) around is the "stateful" part of stateful hot reload. Normally it's a very good thing, as it helps developers code quickly. In this case, though, it's a little confusing. :)

For more information, I highly recommend reading through the source code for:
* [Provider's `of` method](https://github.com/rrousselGit/provider/blob/master/lib/src/provider.dart#L199)
* [InheritedWidget](https://github.com/flutter/flutter/blob/b58c3f0852863417b482147527e8b694243f3b2f/packages/flutter/lib/src/widgets/framework.dart#L1709)
* [Element](https://github.com/flutter/flutter/blob/b58c3f0852863417b482147527e8b694243f3b2f/packages/flutter/lib/src/widgets/framework.dart#L2918)
* [InheritedElement](https://github.com/flutter/flutter/blob/b58c3f0852863417b482147527e8b694243f3b2f/packages/flutter/lib/src/widgets/framework.dart#L5005)
* [BuildContext](https://github.com/flutter/flutter/blob/b58c3f0852863417b482147527e8b694243f3b2f/packages/flutter/lib/src/widgets/framework.dart#L2060)
