### ISSUE TITLE
[Improvement] Size of Material Button is small

### ISSUE THREAD

**Issue by Raj-Dave368** [flutter/samples#568]
### Description 
if the size of the `MaterialButton` in `AnimatedBuilder` [here ](https://github.com/flutter/samples/blob/master/animations/lib/src/basics/05_animated_builder.dart#L49 )Could be large, then the user could more clearly "How beautifully Flutter Turns One Color into Another".

### **instead of this**

![image](https://user-images.githubusercontent.com/54175432/96218543-91ca3980-0fa2-11eb-8b4a-b0c546ab824c.png)

### **it can look like this.**

![image](https://user-images.githubusercontent.com/54175432/96218673-dfdf3d00-0fa2-11eb-87ca-549d57896c22.png)  
![image](https://user-images.githubusercontent.com/54175432/96218688-e79ee180-0fa2-11eb-8404-679410493e3e.png)

**Comment by RedBrogdon** [comment]
Thanks for filing this issue, @Raj-Dave368. I actually wouldn't recommend this change, mostly because having a single button expanded to take up the whole isn't something you'd normally see in an app (nor is it something the Material team would recommend).

Making the button a *little* bigger, though, could be a good change. Doubling it in size, for example.

**Comment by Raj-Dave368** [comment]
Thanks 
Sorry, As I was excited to contribute as a newbie I haven't thought about material design.
But I think issue is still there that it will be better to change colour of large area instead of colour of button.
So what if instead of applying color on button, we apply color on scaffold(background color) and keeping button Size normal.

**Comment by tusharojha** [comment]
@domesticmouse I think this issue can be closed now.

**Comment by AyushBherwani1998** [comment]
Closing, the issue have been fixed in #600
