### ISSUE TITLE
[animations] Need to modify UI/UX and Add some textual content in Animation Sample App

### ISSUE THREAD

**Issue by adarsh-technocrat** [flutter/samples#612]
I think we should improve the UI/UX of the Animation Sample App and add some textual content related to the animations.
there is no textual content added in the app related to the animation which can give users an overview of it.

Including the above points, there are some other points that can be considered while improving the app are:-

**App Home Screen**
1. we can create a card instead of using ListTile which will include:- Name of Animation, About the animation, and Related Links from flutter website.
2. we can add a search bar that will allow the user to search animation by name  (optional feature).

**Animation Detail Screen**
1.  Animation Detail screen should include:- Animation Name which is not included in the current app  (issue  #564 PR is closed),  Detail Description about the animation and playful related animation.

Will create a PR soon if this sounds good. WDYT @domesticmouse @RedBrogdon @AyushBherwani1998?

**Comment by adarsh-technocrat** [comment]
I'm new to open-source contribution please correct me if I'm wrong anywhere creating the issue.

**Comment by RedBrogdon** [comment]
While I appreciate the idea (and the offer to contribute code), I would argue that this is not a good change.

The things you're describing would be useful in a sense, don't get me wrong, but the animations sample is designed specifically to teach people how to use Flutter's animation-related classes. Any additional code that's added is, in a way, just more text that the reader has to parse and understand before they can learn what they need from the app. The codebase for our samples is deliberately kept as small as possible in order to make it quick and easy for readers to find the code that will teach them the desired concepts.
