### ISSUE TITLE
[animations]  Add output of each animation in documentation.

### ISSUE THREAD

**Issue by viralvaghela** [flutter/samples#616]
Hello, it would be nice if we can add an output gif of each animation in the readme.md and will be more clear by just looking at the output(gif) that how it actually works. Will create a PR soon if this sounds good. WDYT  @domesticmouse  @RedBrogdon ?

**Comment by RedBrogdon** [comment]
Interesting. How do you imagine you'd generate the images, and where would they be kept?

**Comment by ibhavikmakwana** [comment]
A suggestion.

Something like this may work @RedBrogdon but more compact?

https://github.com/ibhavikmakwana/FlutterPlayground/blob/master/README.md

https://github.com/ibhavikmakwana/FlutterPlayground/blob/master/preview/staggered_animation.gif

**Comment by viralvaghela** [comment]
@RedBrogdon i can create a "preview" directory and store all GIFs there as @ibhavikmakwana  suggested

**Comment by bharat-1809** [comment]
Hi @viralvaghela if the issue is still available, can I work on it?

**Comment by viralvaghela** [comment]
hello @bharat-1809 i am waiting for the confirmation from @RedBrogdon , after that i will start working on it :) [ it will be my first PR 🤩 So i am really excited ]

**Comment by bharat-1809** [comment]
> hello @bharat-1809 i am waiting for the confirmation from @RedBrogdon , after that i will start working on it :) [ it will be my first PR  So i am really excited ]

Sure @viralvaghela! 👍🏻

**Comment by RedBrogdon** [comment]
(just getting back from end-of-year holidays 🎄)

@viralvaghela, I was actually more concerned with how the images would be generated rather than where they would be stored. I think your idea of having them in the repo is fine, though I'd suggest `/tool/images` rather than creating a new root-level directory.

Have you looked into how to automatically create an animated GIF based on a widget test? The Flutter SDK's docs contain a number of images generated this way. The reason I ask is that it would definitely be better to have an automated method to generate the files rather than something that needs to be done by hand.

**Comment by bharat-1809** [comment]
@RedBrogdon, as you mentioned, I think we can use the workflow used for creating the static assets for the API docs to automatically generate the output files. Like [here](https://github.com/flutter/assets-for-api-docs#creating-new-diagrams), using the [`diagram_capture`](https://github.com/flutter/assets-for-api-docs#creating-new-diagrams) package as done for the docs.

Either we can create a similar workflow for the samples repo or add the required classes to the list in the `assets-for-api-docs` repo and then link the assets here. What do you suggest?
