### ISSUE TITLE
Update Veggieseasons to use CupertinoSearchTextField

### ISSUE THREAD

**Issue by adarsh-technocrat** [flutter/samples#618]
The veggieseasons uses the custom search field which can be replaced with the new CupertinoSearchTextField which was added recently and is available on the dev channel. Since, the veggieseasons is in the experimental directory, I think we can do the changes.

**Comment by RedBrogdon** [comment]
While you're certainly welcome to do so, I'm not sure it would have that much impact. The charts sample will soon be taken out of this repo, and the _tool directory under /web isn't actually a sample -- it's a part of the process used to create the [Visual Samples Index](https://flutter.github.io/samples).

**Comment by RedBrogdon** [comment]
I now realize that you've made two offers to contribute to our repo, and I've turned down both. Please don't let this discourage you from looking for ways to help the Flutter ecosystem. The sample code we maintain here has slightly different requirements than you'd find in regular application code and is often built and maintained in a way that's not obvious unless you're used to it.

If it helps, there's nothing that really makes the code here better or more "official" than applications and samples you find elsewhere. These are just the apps that happen to be maintained by the Flutter team.

**Comment by AyushBherwani1998** [comment]
Hey @RedBrogdon 👋🏼 , I have something he can work on but not sure if this is the right time to do that change.

The veggieseasons uses the custom search field which can be replaced with the new [`CupertinoSearchTextField`](https://master-api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html) which was added recently and is [available on the `dev` channel](https://github.com/flutter/flutter/blob/dev/packages/flutter/lib/src/cupertino/search_field.dart). Since, the veggieseasons is in the experimental directory, I think we can do the changes.

Hey @adarsh-technocrat, if Andrew agrees with the thought feel free to raise an issue and send a PR :)

**Comment by adarsh-technocrat** [comment]
Hello, @AyushBherwani1998  @RedBrogdon  👋🏼 thank you for reverting me back I really want to contribute to the repo but not finding the ways to do so.  Ya sure @AyushBherwani1998  if Andrew agrees with the thought I will definitely raise an issue on the problem and a PR soon.

**Comment by RedBrogdon** [comment]
Seems like a great idea to me. I remember wishing that widget existed two years ago when I originally built the app. 😄 

I'll reopen and rename this issue.

**Comment by AyushBherwani1998** [comment]
I love the fact that Daniel and Xiao working so hard to add new Cupertino Widgets to the framework 😄
