### ISSUE TITLE
Adding basic flutter app for tutorial in CustomPaint.

### ISSUE THREAD

**Issue by SatYu26** [flutter/samples#671]
I would like to create a pull request for a **well commented and descriptive** app in which i have described creating a **background using CustomPaint widget**, which might really be helpful.
Is it fine if i create a PR? i created this  issue as its my first time in open source and i want to contribute to community even if it is baby steps.

**Comment by RedBrogdon** [comment]
Thanks for filing an issue before sending us a PR, @SatYu26. We actually have someone working on a sample for CustomPaint right now, though it's going to land in our flutter/codelabs repo rather than this one.

Please don't let that discourage you from working on your idea for a sample, though, if you're interested in CustomPaint! Just put it in a repo of your own and reach out to me on [Twitter](https://twitter.com/redbrogdon). I'll be happy to help share the word about the project.

**Comment by SatYu26** [comment]
@RedBrogdon Thank you sir. will definitely do that.
