### ISSUE TITLE
A new Flutter Machine learning Sample app

### ISSUE THREAD

**Issue by SatYu26** [flutter/samples#696]
Hello,
So i have been recently working on some basic Machine learning app in flutter using tensorflow lite, and i just noticed that there are no sample apps here regarding that, so is it possible if i land a PR including that app in this repo.?
here is the link to sample repo: [https://github.com/SatYu26/Flutter-X-Mask_Recognition_Model](https://github.com/SatYu26/Flutter-X-Mask_Recognition_Model)
                                                  [https://github.com/SatYu26/Tensorflow-X-Flutter](https://github.com/SatYu26/Tensorflow-X-Flutter)

i will improve UI more and land a PR if permission is granted.

**Comment by RedBrogdon** [comment]
Well I can't claim your app doesn't work, since it correctly identified some of my groceries. 😄 

![image](https://user-images.githubusercontent.com/969662/107096590-f57daa00-67bf-11eb-8c7c-efc5fd9d0b91.png)

This repo is already so big that it's becoming unwieldy, though, which means we can't afford to add any more apps that don't absolutely *have* to live here.

That said, your app is really cool, and I'd like to help get it some attention. Do you mind if I tweet about it and point people to your repo?

**Comment by SatYu26** [comment]
Thank you so much @RedBrogdon .
It will be really amazing if you tweet about it.!!

**Comment by RedBrogdon** [comment]
I'll get on it.
