### ISSUE TITLE
How to integrate multiple flutter modules into an existing native application?

### ISSUE THREAD

**Issue by zhouhao27** [flutter/samples#845]
Based on https://github.com/flutter/samples/tree/master/add_to_app/prebuilt_module/ios_using_prebuilt_module, we can integrate flutter module into an existing application. My question is how to integrate multiple flutter modules into the existing application?

**Comment by RedBrogdon** [comment]
The issue tracker for this repo is intended to cover issues with the samples themselves, rather than answer questions about the SDK. StackOverflow is a better means to get that particular kind of help.

That said, I'm curious about your use case. We do have a sample that shows how to instantiate multiple instances of the Flutter engine:

https://github.com/flutter/samples/blob/master/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/DoubleFlutterActivity.kt

Is your question more about how to include multiple Flutter modules and conditionally instantiate a Flutter Engine pointing to one or the other?
