### ISSUE TITLE
Navigation and Routing sample broken link

### ISSUE THREAD

**Issue by mit-mit** [flutter/samples#865]
https://flutter.github.io/samples/navigation_and_routing.html

Pressing the Source Code gives a broken link.

**Comment by johnpryan** [comment]
Here's a possible fix: https://github.com/flutter/samples/pull/867

This is probably happening because the `<base href="/">` tags are set to
"/" instead of "/samples/web/<SAMPLE_DIR_NAME>/". This makes sense so folks
can download and run locally, but doesn't work when we deploy to GitHub
Pages. I think the other samples are working because they are using an
older version of the `index.html` file created by the Flutter tools without
the base tag in them. We should probably update those as well.

I'm deploying this version to my fork of flutter/samples
<https://github.com/johnpryan/samples/runs/3266308494> so we should be able
to verify this is a working fix
