### ISSUE TITLE
Date Picker TypeError on Form Widgets

### ISSUE THREAD

**Issue by HafidAbnaou** [flutter/samples#932]
In form_widgets.dart, this error is thrown when picking a date
> (type '(DateTime) => void' is not a subtype of type '((dynamic) => void)?')
A possible fix that worked for me is changing:
`final ValueChanged<T>? onChanged;`
to:
`final ValueChanged<DateTime>? onChanged;`

**Comment by RedBrogdon** [comment]
Thanks for reporting the issue, @HafidAbnaou!

After investigating, it turned out that the type parameter wasn't included in the definition of the State object class (`extends State<_FormDatePicker>` should have been `extends <_FormDatePicker<T>>`). So what was a `ValueChanged<T>` within the scope of `_FormDatePicker` was a `ValueChanged<dynamic>` when referenced from inside the State class.

After more investigating, it turned out the type parameter wasn't really being used, so I took it out entirely. 😄
