### ISSUE TITLE
Photo Search: Menu items have rounded corners

### ISSUE THREAD

**Issue by timsneath** [flutter/samples#992]
On Windows 11, the photo search app menus have rounded corners:
![image](https://user-images.githubusercontent.com/2319867/149675163-f6709c2d-569c-4003-b8e4-7055e2eff22c.png)

Use `DwmSetWindowAttribute` to set rectangular windows, as follows:

```dart
final attr = DWMWINDOWATTRIBUTE.DWMWA_WINDOW_CORNER_PREFERENCE;
final pref = calloc<Uint32>()
  ..value = DWM_WINDOW_CORNER_PREFERENCE.DWMWCP_DONOTROUND;

DwmSetWindowAttribute(hwnd, attr, pref, sizeOf<Uint32>());

calloc.free(pref);
```

**Comment by gaurav1903** [comment]
What is the exact issue and how to reproduce it?

**Comment by domesticmouse** [comment]
Thanks for the report @timsneath. This almost feels like something we should be fixing in the win32 runner, not the sample code.

Thoughts @csells?

**Comment by csells** [comment]
Can we fix it in the sample until we have it fixed in the embedding?

fyi @cbracken @gspencergoog

**Comment by domesticmouse** [comment]
@timsneath Can you give guidance on where I need to make this modification? I'm guessing since this is a change to `hwnd`, and I'm guessing the menu drop downs are individual windows, I'm guessing the fix has to be added to https://github.com/google/flutter-desktop-embedding/tree/master/plugins/menubar/windows?

/cc @stuartmorgan who probably knows a thing or two about this.

**Comment by stuartmorgan** [comment]
`menubar` is creating the menus using standard Win32 APIs for creating menus. It never interacts directly with the underlying HWNDs.

Why is this a bug? Isn't this just how Windows 11 works?

**Comment by timsneath** [comment]
Hmm... is your window maximized, @domesticmouse? What does `winver` report for your version? 

I'm running the Windows Insider builds, haven't knowingly changed any defaults. But it's possible that there's something weird about the current build in this regard.

Here are the instructions on what to do with menus, @stuartmorgan: 
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners#example-4--rounding-the-corners-of-a-menu-with-a-small-radius---c

If we're doing that (or that's being done automatically), then perhaps we're good?

**Comment by stuartmorgan** [comment]
> Here are the instructions on what to do with menus, @stuartmorgan: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners#example-4--rounding-the-corners-of-a-menu-with-a-small-radius---c

That's about making custom menus:
> By default, menus are pop-up windows, which do not get rounded. If your app creates a custom menu and you want it to follow the rounding policy of other standard menus [...]

It explains how to make a menu that's not made using normal menu APIs look rounded in order to match those that are made using normal menu APIs.

`menubar` is, as I said above, using standard menus. And it's already rounded in your screenshot.

> If we're doing that (or that's being done automatically), then perhaps we're good?

My confusions here is your bug report is that we *are* getting the standard behavior (which is apparently now rounded). I still don't understand why that's a bug.

**Comment by domesticmouse** [comment]
<img width="347" alt="winver" src="https://user-images.githubusercontent.com/30503/150030251-3ec594c5-2213-419d-a713-5b97f3ade69a.png">

**Comment by domesticmouse** [comment]
From [Apply rounded corners in desktop apps for Windows 11](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners): 

**Note**

By design, apps are not rounded when maximized, snapped, running in a Virtual Machine (VM), running on a Windows Virtual Desktop (WVD), or running as a Windows Defender Application Guard (WDAG) window.

Looks like I need to upgrade my machine, instead of using the Developer VM. Yay.

**Comment by timsneath** [comment]
But yeah, this might be by design, which is Stuart's point.

**Comment by domesticmouse** [comment]
Now that I have upgraded my desktop to Windows 11, I can safely say that some apps have rounded menus. Windows Terminal and Google Chrome both show rounded menus, while VSCode and GitHub desktop tooling do not.

It looks like rounded menus on Win11 is going to be a hot mess. At this point I'm closing this as WAI.
